### ISSUE TITLE
replace pdf-parse

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#1244]
**Describe the bug**

pdf-parse looks like complete unsupported and it use an old pdf.js version.

**Expected behavior**

A maintained alternative of pdf-parse should used with newer pdf.js.

**Additional context**

Currently i'm look into it, if we just can use pdf.js without wrapper. Since pdf.js closed some issues.
I copied the tests of pdf-parse and write a new wrapper based on the new version with the npm package https://www.npmjs.com/package/pdfjs-dist. I make a pull request if it is simple to integrate. 

**Some links**

https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/package.json
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/ReadPdf.node.ts
https://gitlab.com/autokent/pdf-parse

**Update 2020-12-17**

I readed alot about transform in textContent and how to read pdf with pdfjs.
I implemented a dirty js library to test it out and it works fine.
Currently i try to implement a tool that get some outline information (bookmarks).
After that i translate to code to typescript.
But at the moment I don’t know whether I should create an external library with a test environment which will then be integrated or whether the implementation should be built directly into the node direct on pdfjs without extra dependencies

**Update 2021-02-02**

Through other projects, it took a little longer, but the rewriting in typescript is progressing. It just depends on this pull request:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50979

**Update 2021-04-15**

Sorry for the delay, but I have now built a typescript project.
(https://github.com/lublak/pdfdataextract)
There are still 3.5 things missing.

**Update 2022-01-17**

And another delay (sry). But the development has begun and we are gradually replacing it. Plus more functions that were missing will be added.
Other functions will also follow, but they still need a bit of work: https://github.com/lublak/pdfdataextract/tree/contentinfoextractor

**Todos**

- [x] tests (jest is already done, only pdf examples are missing)
- [x] npm release
- [ ] rewriting the current node

and the 3.5 thing: 
- [x] improve the code

**Comment by Joffcom** [comment]
Hey @lublak,

How are you getting on with this one?

**Comment by lublak** [comment]
@Joffcom hey!
In theory, pdfdataextract is ready and is already being used by various people. The current issues are rather new functions that I would like to implement in pdfdataextract, but this will take some time.
But the current state can already be used: https://github.com/lublak/pdfdataextract/wiki

That is actually I only have to replace the knot, but I'm honest, I have lost sight of it. Should not be a problem because pdfdataextract is similar to pdf-parse. https://github.com/lublak/pdfdataextract/wiki/PdfData#extract

Sorry about the delay

**Comment by nzidol** [comment]
Have a quick and dirty working version here that is a direct replacement of pdf-parse with pdf-js https://github.com/nzidol/n8n-nodes-readPDFForm also grabs the form data...

**Comment by Joffcom** [comment]
Hey @nzidol,

That is neat, is it published to the community node repo?

I am also going to mark this one as closed for now as it isn't a bug as such and the PR was closed out with the intention of us rebuilding the node in the future.

**Comment by nzidol** [comment]
Just finished a [writePdfForm](https://www.npmjs.com/package/n8n-nodes-writepdfform) node using [pdf-lib ](https://www.npmjs.com/package/pdf-lib)

**Comment by danielo515** [comment]
Why have this been closed without updating the library to, for example, allow to read encrypted PDFs?
